### ISSUE TITLE
cannot load module

### ISSUE THREAD

**Issue by droidrider** [i-ky/effluence#4]
Hello everyone,

I have a issue when zabbix try to load this module.
The OS is Centos 7.4

log :
````bash
 25902:20181018:110619.302 using configuration file: /etc/zabbix/zabbix_server.conf
 25902:20181018:110619.302 cannot load module "effluence.so": /usr/lib/zabbix/modules/effluence.so: undefined symbol: yaml_parser_set_input_file
 25902:20181018:110619.302 loading modules failed, exiting...
````
This is my configuration file : 

````yaml
[dbl, uint]: # for both Numeric (float) and Numeric (unsigned)
  url: http://10.2.20.39:8086
  db: numeric
  user: zabbix
````
I have installed these packages :
 - libyaml-0.1.4-11.el7_0.x86_64
 - libcurl-7.29.0-42.el7.x86_64

Has anyone ever had this problem?
Thank you for your work
